/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { DividerProps, GridProps, HeadingProps, SelectFieldProps, SwitchFieldProps, TextFieldProps, TextProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type NewPatientCreateFormInputValues = {
    date?: string;
    last_name?: string;
    first_name?: string;
    date_of_birth?: string;
    gender?: string;
    marital_status?: string;
    ethnicity?: string;
    race?: string;
    primary_language?: string;
    address?: string;
    city?: string;
    state?: string;
    zip?: string;
    home_phone?: string;
    work_phone?: string;
    mobile_phone?: string;
    email?: string;
    social_security?: string;
    employer?: string;
    education?: string;
    veteran?: boolean;
    occupatin?: string;
    full_time?: boolean;
    preferred_pharmacy?: string;
    insurance_primary_name?: string;
    insurance_primary_id?: string;
    insurance_primary_group?: string;
    insurance_primary_address?: string;
    insurance_primary_phone?: string;
    insurance_primary_insured_person?: string;
    insurance_primary_insured_person_relation?: string;
    insurance_secondary?: string;
    insurance_secondary_id?: string;
    insurance_secondary_group?: string;
    insurance_secondary_address?: string;
    insurance_secondary_phone?: string;
    primary_care_physician_name?: string;
    primary_care_physician_phone?: string;
    referring_physician_name?: string;
    referring_physician_phone?: string;
    emergency_contact_name?: string;
    emergency_contact_phone?: string;
    emergency_contact_relationship?: string;
    signature_page_1?: string;
    signature_page_1_date?: string;
};
export declare type NewPatientCreateFormValidationValues = {
    date?: ValidationFunction<string>;
    last_name?: ValidationFunction<string>;
    first_name?: ValidationFunction<string>;
    date_of_birth?: ValidationFunction<string>;
    gender?: ValidationFunction<string>;
    marital_status?: ValidationFunction<string>;
    ethnicity?: ValidationFunction<string>;
    race?: ValidationFunction<string>;
    primary_language?: ValidationFunction<string>;
    address?: ValidationFunction<string>;
    city?: ValidationFunction<string>;
    state?: ValidationFunction<string>;
    zip?: ValidationFunction<string>;
    home_phone?: ValidationFunction<string>;
    work_phone?: ValidationFunction<string>;
    mobile_phone?: ValidationFunction<string>;
    email?: ValidationFunction<string>;
    social_security?: ValidationFunction<string>;
    employer?: ValidationFunction<string>;
    education?: ValidationFunction<string>;
    veteran?: ValidationFunction<boolean>;
    occupatin?: ValidationFunction<string>;
    full_time?: ValidationFunction<boolean>;
    preferred_pharmacy?: ValidationFunction<string>;
    insurance_primary_name?: ValidationFunction<string>;
    insurance_primary_id?: ValidationFunction<string>;
    insurance_primary_group?: ValidationFunction<string>;
    insurance_primary_address?: ValidationFunction<string>;
    insurance_primary_phone?: ValidationFunction<string>;
    insurance_primary_insured_person?: ValidationFunction<string>;
    insurance_primary_insured_person_relation?: ValidationFunction<string>;
    insurance_secondary?: ValidationFunction<string>;
    insurance_secondary_id?: ValidationFunction<string>;
    insurance_secondary_group?: ValidationFunction<string>;
    insurance_secondary_address?: ValidationFunction<string>;
    insurance_secondary_phone?: ValidationFunction<string>;
    primary_care_physician_name?: ValidationFunction<string>;
    primary_care_physician_phone?: ValidationFunction<string>;
    referring_physician_name?: ValidationFunction<string>;
    referring_physician_phone?: ValidationFunction<string>;
    emergency_contact_name?: ValidationFunction<string>;
    emergency_contact_phone?: ValidationFunction<string>;
    emergency_contact_relationship?: ValidationFunction<string>;
    signature_page_1?: ValidationFunction<string>;
    signature_page_1_date?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type NewPatientCreateFormOverridesProps = {
    NewPatientCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    SectionalElement0?: PrimitiveOverrideProps<HeadingProps>;
    date?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid2?: PrimitiveOverrideProps<GridProps>;
    last_name?: PrimitiveOverrideProps<TextFieldProps>;
    first_name?: PrimitiveOverrideProps<TextFieldProps>;
    date_of_birth?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid3?: PrimitiveOverrideProps<GridProps>;
    gender?: PrimitiveOverrideProps<TextFieldProps>;
    marital_status?: PrimitiveOverrideProps<SelectFieldProps>;
    RowGrid4?: PrimitiveOverrideProps<GridProps>;
    ethnicity?: PrimitiveOverrideProps<TextFieldProps>;
    race?: PrimitiveOverrideProps<TextFieldProps>;
    primary_language?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid5?: PrimitiveOverrideProps<GridProps>;
    address?: PrimitiveOverrideProps<TextFieldProps>;
    city?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid6?: PrimitiveOverrideProps<GridProps>;
    state?: PrimitiveOverrideProps<TextFieldProps>;
    zip?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid7?: PrimitiveOverrideProps<GridProps>;
    home_phone?: PrimitiveOverrideProps<TextFieldProps>;
    work_phone?: PrimitiveOverrideProps<TextFieldProps>;
    mobile_phone?: PrimitiveOverrideProps<TextFieldProps>;
    email?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid9?: PrimitiveOverrideProps<GridProps>;
    social_security?: PrimitiveOverrideProps<TextFieldProps>;
    employer?: PrimitiveOverrideProps<TextFieldProps>;
    education?: PrimitiveOverrideProps<SelectFieldProps>;
    veteran?: PrimitiveOverrideProps<SwitchFieldProps>;
    RowGrid12?: PrimitiveOverrideProps<GridProps>;
    occupatin?: PrimitiveOverrideProps<TextFieldProps>;
    full_time?: PrimitiveOverrideProps<SwitchFieldProps>;
    preferred_pharmacy?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement2?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement3?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement1?: PrimitiveOverrideProps<HeadingProps>;
    insurance_primary_name?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid18?: PrimitiveOverrideProps<GridProps>;
    insurance_primary_id?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_group?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid19?: PrimitiveOverrideProps<GridProps>;
    insurance_primary_address?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_phone?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_insured_person?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_insured_person_relation?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_secondary?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid23?: PrimitiveOverrideProps<GridProps>;
    insurance_secondary_id?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_secondary_group?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid24?: PrimitiveOverrideProps<GridProps>;
    insurance_secondary_address?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_secondary_phone?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement4?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement5?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement6?: PrimitiveOverrideProps<HeadingProps>;
    RowGrid28?: PrimitiveOverrideProps<GridProps>;
    primary_care_physician_name?: PrimitiveOverrideProps<TextFieldProps>;
    primary_care_physician_phone?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid29?: PrimitiveOverrideProps<GridProps>;
    referring_physician_name?: PrimitiveOverrideProps<TextFieldProps>;
    referring_physician_phone?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement8?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement7?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement9?: PrimitiveOverrideProps<HeadingProps>;
    RowGrid33?: PrimitiveOverrideProps<GridProps>;
    emergency_contact_name?: PrimitiveOverrideProps<TextFieldProps>;
    emergency_contact_phone?: PrimitiveOverrideProps<TextFieldProps>;
    emergency_contact_relationship?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement10?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement11?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement12?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement13?: PrimitiveOverrideProps<TextProps>;
    RowGrid39?: PrimitiveOverrideProps<GridProps>;
    signature_page_1?: PrimitiveOverrideProps<TextFieldProps>;
    signature_page_1_date?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type NewPatientCreateFormProps = React.PropsWithChildren<{
    overrides?: NewPatientCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: NewPatientCreateFormInputValues) => NewPatientCreateFormInputValues;
    onSuccess?: (fields: NewPatientCreateFormInputValues) => void;
    onError?: (fields: NewPatientCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: NewPatientCreateFormInputValues) => NewPatientCreateFormInputValues;
    onValidate?: NewPatientCreateFormValidationValues;
} & React.CSSProperties>;
export default function NewPatientCreateForm(props: NewPatientCreateFormProps): React.ReactElement;
