/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { AutocompleteProps, DividerProps, GridProps, HeadingProps, SelectFieldProps, SliderFieldProps, SwitchFieldProps, TextAreaFieldProps, TextFieldProps, TextProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type NewPatientCreateFormInputValues = {
    date?: string;
    last_name?: string;
    first_name?: string;
    date_of_birth?: string;
    gender?: string;
    marital_status?: string;
    ethnicity?: string;
    race?: string;
    primary_language?: string;
    address?: string;
    city?: string;
    state?: string;
    zip?: string;
    home_phone?: string;
    work_phone?: string;
    mobile_phone?: string;
    email?: string;
    social_security?: string;
    employer?: string;
    education?: string;
    veteran?: boolean;
    occupatin?: string;
    full_time?: boolean;
    preferred_pharmacy?: string;
    insurance_primary_name?: string;
    insurance_primary_id?: string;
    insurance_primary_group?: string;
    insurance_primary_address?: string;
    insurance_primary_phone?: string;
    insurance_primary_insured_person?: string;
    insurance_primary_insured_person_relation?: string;
    insurance_secondary?: string;
    insurance_secondary_id?: string;
    insurance_secondary_group?: string;
    insurance_secondary_address?: string;
    insurance_secondary_phone?: string;
    primary_care_physician_name?: string;
    primary_care_physician_phone?: string;
    referring_physician_name?: string;
    referring_physician_phone?: string;
    emergency_contact_name?: string;
    emergency_contact_phone?: string;
    emergency_contact_relationship?: string;
    signature_page_1?: string;
    signature_page_1_date?: string;
    ph_briefly_describe_present_symptoms?: string;
    ph_previous_treatment_for_problem?: string;
    ph_current_medicine_1?: string;
    ph_allergy_to_med?: boolean;
    ph_allergy_to_med_list?: string;
    ph_rh_history_osteoarthritis?: string;
    ph_rh_history_gout?: string;
    ph_rh_history_juvenile_arthritis?: string;
    ph_rh_history_vasculitis?: string;
    ph_rh_history_lupus?: string;
    ph_rh_history_rheumatoid?: string;
    ph_rh_history_spondyloarthropathy?: string;
    ph_rh_history_osteoporosis?: string;
    ph_past_medical_history?: string;
    ph_past_surgery_history?: string;
    ph_smoke?: string;
    ph_drugs?: string;
    ph_alcohol?: string;
    ph_alcohol_weekly?: string;
    ph_sleep?: string;
    ph_exercise?: string;
    ph_travel?: string;
    ph_pregnant?: string;
    ph_live_births?: string;
    ph_complications?: string;
    ph_symptoms?: string;
    ad_people_in_household?: string;
    ad_who_shopping?: string;
    ad_housework?: string;
    ad_hardest_thing?: string;
    ad_ability_stand_up_chair?: string;
    ad_ability_walk_outdoors_flat?: string;
    ad_ability_get_on_toilet?: string;
    ad_ability_reach_5_pound?: string;
    ad_ability_car_doors?: string;
    ad_ability_outside_work?: string;
    ad_ability_wait_in_line?: string;
    ad_ability_lift_heavy?: string;
    ad_ability_lift_heavier?: string;
    ad_ability_climb_2_flights?: string;
    ad_aids_devices_activities?: string[];
    ad_categories_help?: string[];
    ad_daily_pain_scale?: number;
    ad_how_well_doing_scale?: number;
};
export declare type NewPatientCreateFormValidationValues = {
    date?: ValidationFunction<string>;
    last_name?: ValidationFunction<string>;
    first_name?: ValidationFunction<string>;
    date_of_birth?: ValidationFunction<string>;
    gender?: ValidationFunction<string>;
    marital_status?: ValidationFunction<string>;
    ethnicity?: ValidationFunction<string>;
    race?: ValidationFunction<string>;
    primary_language?: ValidationFunction<string>;
    address?: ValidationFunction<string>;
    city?: ValidationFunction<string>;
    state?: ValidationFunction<string>;
    zip?: ValidationFunction<string>;
    home_phone?: ValidationFunction<string>;
    work_phone?: ValidationFunction<string>;
    mobile_phone?: ValidationFunction<string>;
    email?: ValidationFunction<string>;
    social_security?: ValidationFunction<string>;
    employer?: ValidationFunction<string>;
    education?: ValidationFunction<string>;
    veteran?: ValidationFunction<boolean>;
    occupatin?: ValidationFunction<string>;
    full_time?: ValidationFunction<boolean>;
    preferred_pharmacy?: ValidationFunction<string>;
    insurance_primary_name?: ValidationFunction<string>;
    insurance_primary_id?: ValidationFunction<string>;
    insurance_primary_group?: ValidationFunction<string>;
    insurance_primary_address?: ValidationFunction<string>;
    insurance_primary_phone?: ValidationFunction<string>;
    insurance_primary_insured_person?: ValidationFunction<string>;
    insurance_primary_insured_person_relation?: ValidationFunction<string>;
    insurance_secondary?: ValidationFunction<string>;
    insurance_secondary_id?: ValidationFunction<string>;
    insurance_secondary_group?: ValidationFunction<string>;
    insurance_secondary_address?: ValidationFunction<string>;
    insurance_secondary_phone?: ValidationFunction<string>;
    primary_care_physician_name?: ValidationFunction<string>;
    primary_care_physician_phone?: ValidationFunction<string>;
    referring_physician_name?: ValidationFunction<string>;
    referring_physician_phone?: ValidationFunction<string>;
    emergency_contact_name?: ValidationFunction<string>;
    emergency_contact_phone?: ValidationFunction<string>;
    emergency_contact_relationship?: ValidationFunction<string>;
    signature_page_1?: ValidationFunction<string>;
    signature_page_1_date?: ValidationFunction<string>;
    ph_briefly_describe_present_symptoms?: ValidationFunction<string>;
    ph_previous_treatment_for_problem?: ValidationFunction<string>;
    ph_current_medicine_1?: ValidationFunction<string>;
    ph_allergy_to_med?: ValidationFunction<boolean>;
    ph_allergy_to_med_list?: ValidationFunction<string>;
    ph_rh_history_osteoarthritis?: ValidationFunction<string>;
    ph_rh_history_gout?: ValidationFunction<string>;
    ph_rh_history_juvenile_arthritis?: ValidationFunction<string>;
    ph_rh_history_vasculitis?: ValidationFunction<string>;
    ph_rh_history_lupus?: ValidationFunction<string>;
    ph_rh_history_rheumatoid?: ValidationFunction<string>;
    ph_rh_history_spondyloarthropathy?: ValidationFunction<string>;
    ph_rh_history_osteoporosis?: ValidationFunction<string>;
    ph_past_medical_history?: ValidationFunction<string>;
    ph_past_surgery_history?: ValidationFunction<string>;
    ph_smoke?: ValidationFunction<string>;
    ph_drugs?: ValidationFunction<string>;
    ph_alcohol?: ValidationFunction<string>;
    ph_alcohol_weekly?: ValidationFunction<string>;
    ph_sleep?: ValidationFunction<string>;
    ph_exercise?: ValidationFunction<string>;
    ph_travel?: ValidationFunction<string>;
    ph_pregnant?: ValidationFunction<string>;
    ph_live_births?: ValidationFunction<string>;
    ph_complications?: ValidationFunction<string>;
    ph_symptoms?: ValidationFunction<string>;
    ad_people_in_household?: ValidationFunction<string>;
    ad_who_shopping?: ValidationFunction<string>;
    ad_housework?: ValidationFunction<string>;
    ad_hardest_thing?: ValidationFunction<string>;
    ad_ability_stand_up_chair?: ValidationFunction<string>;
    ad_ability_walk_outdoors_flat?: ValidationFunction<string>;
    ad_ability_get_on_toilet?: ValidationFunction<string>;
    ad_ability_reach_5_pound?: ValidationFunction<string>;
    ad_ability_car_doors?: ValidationFunction<string>;
    ad_ability_outside_work?: ValidationFunction<string>;
    ad_ability_wait_in_line?: ValidationFunction<string>;
    ad_ability_lift_heavy?: ValidationFunction<string>;
    ad_ability_lift_heavier?: ValidationFunction<string>;
    ad_ability_climb_2_flights?: ValidationFunction<string>;
    ad_aids_devices_activities?: ValidationFunction<string>;
    ad_categories_help?: ValidationFunction<string>;
    ad_daily_pain_scale?: ValidationFunction<number>;
    ad_how_well_doing_scale?: ValidationFunction<number>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type NewPatientCreateFormOverridesProps = {
    NewPatientCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    SectionalElement0?: PrimitiveOverrideProps<HeadingProps>;
    date?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid2?: PrimitiveOverrideProps<GridProps>;
    last_name?: PrimitiveOverrideProps<TextFieldProps>;
    first_name?: PrimitiveOverrideProps<TextFieldProps>;
    date_of_birth?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid3?: PrimitiveOverrideProps<GridProps>;
    gender?: PrimitiveOverrideProps<TextFieldProps>;
    marital_status?: PrimitiveOverrideProps<SelectFieldProps>;
    RowGrid4?: PrimitiveOverrideProps<GridProps>;
    ethnicity?: PrimitiveOverrideProps<TextFieldProps>;
    race?: PrimitiveOverrideProps<TextFieldProps>;
    primary_language?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid5?: PrimitiveOverrideProps<GridProps>;
    address?: PrimitiveOverrideProps<TextFieldProps>;
    city?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid6?: PrimitiveOverrideProps<GridProps>;
    state?: PrimitiveOverrideProps<TextFieldProps>;
    zip?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid7?: PrimitiveOverrideProps<GridProps>;
    home_phone?: PrimitiveOverrideProps<TextFieldProps>;
    work_phone?: PrimitiveOverrideProps<TextFieldProps>;
    mobile_phone?: PrimitiveOverrideProps<TextFieldProps>;
    email?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid9?: PrimitiveOverrideProps<GridProps>;
    social_security?: PrimitiveOverrideProps<TextFieldProps>;
    employer?: PrimitiveOverrideProps<TextFieldProps>;
    education?: PrimitiveOverrideProps<SelectFieldProps>;
    veteran?: PrimitiveOverrideProps<SwitchFieldProps>;
    occupatin?: PrimitiveOverrideProps<TextFieldProps>;
    full_time?: PrimitiveOverrideProps<SwitchFieldProps>;
    preferred_pharmacy?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement2?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement3?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement1?: PrimitiveOverrideProps<HeadingProps>;
    insurance_primary_name?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid19?: PrimitiveOverrideProps<GridProps>;
    insurance_primary_id?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_group?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid20?: PrimitiveOverrideProps<GridProps>;
    insurance_primary_address?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_phone?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_insured_person?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_primary_insured_person_relation?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_secondary?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid24?: PrimitiveOverrideProps<GridProps>;
    insurance_secondary_id?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_secondary_group?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid25?: PrimitiveOverrideProps<GridProps>;
    insurance_secondary_address?: PrimitiveOverrideProps<TextFieldProps>;
    insurance_secondary_phone?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement4?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement5?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement6?: PrimitiveOverrideProps<HeadingProps>;
    RowGrid29?: PrimitiveOverrideProps<GridProps>;
    primary_care_physician_name?: PrimitiveOverrideProps<TextFieldProps>;
    primary_care_physician_phone?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid30?: PrimitiveOverrideProps<GridProps>;
    referring_physician_name?: PrimitiveOverrideProps<TextFieldProps>;
    referring_physician_phone?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement8?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement7?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement9?: PrimitiveOverrideProps<HeadingProps>;
    RowGrid34?: PrimitiveOverrideProps<GridProps>;
    emergency_contact_name?: PrimitiveOverrideProps<TextFieldProps>;
    emergency_contact_phone?: PrimitiveOverrideProps<TextFieldProps>;
    emergency_contact_relationship?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement10?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement11?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement12?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement13?: PrimitiveOverrideProps<TextProps>;
    RowGrid40?: PrimitiveOverrideProps<GridProps>;
    signature_page_1?: PrimitiveOverrideProps<TextFieldProps>;
    signature_page_1_date?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement15?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement14?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement90?: PrimitiveOverrideProps<HeadingProps>;
    ph_briefly_describe_present_symptoms?: PrimitiveOverrideProps<TextAreaFieldProps>;
    ph_previous_treatment_for_problem?: PrimitiveOverrideProps<TextAreaFieldProps>;
    ph_current_medicine_1?: PrimitiveOverrideProps<TextAreaFieldProps>;
    ph_allergy_to_med?: PrimitiveOverrideProps<SwitchFieldProps>;
    ph_allergy_to_med_list?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement17?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement16?: PrimitiveOverrideProps<TextProps>;
    RowGrid51?: PrimitiveOverrideProps<GridProps>;
    ph_rh_history_osteoarthritis?: PrimitiveOverrideProps<TextFieldProps>;
    ph_rh_history_gout?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid52?: PrimitiveOverrideProps<GridProps>;
    ph_rh_history_juvenile_arthritis?: PrimitiveOverrideProps<TextFieldProps>;
    ph_rh_history_vasculitis?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid53?: PrimitiveOverrideProps<GridProps>;
    ph_rh_history_lupus?: PrimitiveOverrideProps<TextFieldProps>;
    ph_rh_history_rheumatoid?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid54?: PrimitiveOverrideProps<GridProps>;
    ph_rh_history_spondyloarthropathy?: PrimitiveOverrideProps<TextFieldProps>;
    ph_rh_history_osteoporosis?: PrimitiveOverrideProps<TextFieldProps>;
    ph_past_medical_history?: PrimitiveOverrideProps<TextAreaFieldProps>;
    ph_past_surgery_history?: PrimitiveOverrideProps<TextAreaFieldProps>;
    RowGrid57?: PrimitiveOverrideProps<GridProps>;
    ph_smoke?: PrimitiveOverrideProps<SelectFieldProps>;
    ph_drugs?: PrimitiveOverrideProps<SelectFieldProps>;
    RowGrid58?: PrimitiveOverrideProps<GridProps>;
    ph_alcohol?: PrimitiveOverrideProps<SelectFieldProps>;
    ph_alcohol_weekly?: PrimitiveOverrideProps<TextFieldProps>;
    ph_sleep?: PrimitiveOverrideProps<TextFieldProps>;
    ph_exercise?: PrimitiveOverrideProps<TextFieldProps>;
    ph_travel?: PrimitiveOverrideProps<TextFieldProps>;
    RowGrid62?: PrimitiveOverrideProps<GridProps>;
    ph_pregnant?: PrimitiveOverrideProps<SelectFieldProps>;
    ph_live_births?: PrimitiveOverrideProps<TextFieldProps>;
    ph_complications?: PrimitiveOverrideProps<TextFieldProps>;
    ph_symptoms?: PrimitiveOverrideProps<TextAreaFieldProps>;
    SectionalElement18?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement19?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement900?: PrimitiveOverrideProps<HeadingProps>;
    ad_people_in_household?: PrimitiveOverrideProps<TextAreaFieldProps>;
    RowGrid69?: PrimitiveOverrideProps<GridProps>;
    ad_who_shopping?: PrimitiveOverrideProps<TextFieldProps>;
    ad_housework?: PrimitiveOverrideProps<TextFieldProps>;
    ad_hardest_thing?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement120?: PrimitiveOverrideProps<HeadingProps>;
    ad_ability_stand_up_chair?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_walk_outdoors_flat?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_get_on_toilet?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_reach_5_pound?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_car_doors?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_outside_work?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_wait_in_line?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_lift_heavy?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_lift_heavier?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_ability_climb_2_flights?: PrimitiveOverrideProps<SelectFieldProps>;
    ad_aids_devices_activities?: PrimitiveOverrideProps<AutocompleteProps>;
    ad_categories_help?: PrimitiveOverrideProps<AutocompleteProps>;
    ad_daily_pain_scale?: PrimitiveOverrideProps<SliderFieldProps>;
    ad_how_well_doing_scale?: PrimitiveOverrideProps<SliderFieldProps>;
} & EscapeHatchProps;
export declare type NewPatientCreateFormProps = React.PropsWithChildren<{
    overrides?: NewPatientCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: NewPatientCreateFormInputValues) => NewPatientCreateFormInputValues;
    onSuccess?: (fields: NewPatientCreateFormInputValues) => void;
    onError?: (fields: NewPatientCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: NewPatientCreateFormInputValues) => NewPatientCreateFormInputValues;
    onValidate?: NewPatientCreateFormValidationValues;
} & React.CSSProperties>;
export default function NewPatientCreateForm(props: NewPatientCreateFormProps): React.ReactElement;
