/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreatePatientHistoryInput = {
  id?: string | null,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  ph_briefly_describe_present_symptoms: string,
  ph_previous_treatment_for_problem?: string | null,
  ph_current_medicines: string,
  ph_allergy_to_med: boolean,
  ph_allergy_to_med_list?: string | null,
  ph_rh_history_osteoarthritis?: string | null,
  ph_rh_history_gout?: string | null,
  ph_rh_history_juvenile_arthritis?: string | null,
  ph_rh_history_vasculitis?: string | null,
  ph_rh_history_lupus?: string | null,
  ph_rh_history_rheumatoid?: string | null,
  ph_rh_history_spondyloarthropathy?: string | null,
  ph_rh_history_osteoporosis?: string | null,
  ph_past_medical_history?: string | null,
  ph_past_surgery_history?: string | null,
  ph_smoke: string,
  ph_drugs: string,
  ph_alcohol: string,
  ph_alcohol_weekly?: string | null,
  ph_sleep?: string | null,
  ph_exercise?: string | null,
  ph_travel?: string | null,
  ph_pregnant?: string | null,
  ph_live_births?: string | null,
  ph_complications?: string | null,
  ad_people_in_household?: string | null,
  ph_symptoms: Array< string >,
};

export type ModelPatientHistoryConditionInput = {
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  ph_briefly_describe_present_symptoms?: ModelStringInput | null,
  ph_previous_treatment_for_problem?: ModelStringInput | null,
  ph_current_medicines?: ModelStringInput | null,
  ph_allergy_to_med?: ModelBooleanInput | null,
  ph_allergy_to_med_list?: ModelStringInput | null,
  ph_rh_history_osteoarthritis?: ModelStringInput | null,
  ph_rh_history_gout?: ModelStringInput | null,
  ph_rh_history_juvenile_arthritis?: ModelStringInput | null,
  ph_rh_history_vasculitis?: ModelStringInput | null,
  ph_rh_history_lupus?: ModelStringInput | null,
  ph_rh_history_rheumatoid?: ModelStringInput | null,
  ph_rh_history_spondyloarthropathy?: ModelStringInput | null,
  ph_rh_history_osteoporosis?: ModelStringInput | null,
  ph_past_medical_history?: ModelStringInput | null,
  ph_past_surgery_history?: ModelStringInput | null,
  ph_smoke?: ModelStringInput | null,
  ph_drugs?: ModelStringInput | null,
  ph_alcohol?: ModelStringInput | null,
  ph_alcohol_weekly?: ModelStringInput | null,
  ph_sleep?: ModelStringInput | null,
  ph_exercise?: ModelStringInput | null,
  ph_travel?: ModelStringInput | null,
  ph_pregnant?: ModelStringInput | null,
  ph_live_births?: ModelStringInput | null,
  ph_complications?: ModelStringInput | null,
  ad_people_in_household?: ModelStringInput | null,
  ph_symptoms?: ModelStringInput | null,
  and?: Array< ModelPatientHistoryConditionInput | null > | null,
  or?: Array< ModelPatientHistoryConditionInput | null > | null,
  not?: ModelPatientHistoryConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type PatientHistory = {
  __typename: "PatientHistory",
  id: string,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  ph_briefly_describe_present_symptoms: string,
  ph_previous_treatment_for_problem?: string | null,
  ph_current_medicines: string,
  ph_allergy_to_med: boolean,
  ph_allergy_to_med_list?: string | null,
  ph_rh_history_osteoarthritis?: string | null,
  ph_rh_history_gout?: string | null,
  ph_rh_history_juvenile_arthritis?: string | null,
  ph_rh_history_vasculitis?: string | null,
  ph_rh_history_lupus?: string | null,
  ph_rh_history_rheumatoid?: string | null,
  ph_rh_history_spondyloarthropathy?: string | null,
  ph_rh_history_osteoporosis?: string | null,
  ph_past_medical_history?: string | null,
  ph_past_surgery_history?: string | null,
  ph_smoke: string,
  ph_drugs: string,
  ph_alcohol: string,
  ph_alcohol_weekly?: string | null,
  ph_sleep?: string | null,
  ph_exercise?: string | null,
  ph_travel?: string | null,
  ph_pregnant?: string | null,
  ph_live_births?: string | null,
  ph_complications?: string | null,
  ad_people_in_household?: string | null,
  ph_symptoms: Array< string >,
  createdAt: string,
  updatedAt: string,
};

export type UpdatePatientHistoryInput = {
  id: string,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
  ph_briefly_describe_present_symptoms?: string | null,
  ph_previous_treatment_for_problem?: string | null,
  ph_current_medicines?: string | null,
  ph_allergy_to_med?: boolean | null,
  ph_allergy_to_med_list?: string | null,
  ph_rh_history_osteoarthritis?: string | null,
  ph_rh_history_gout?: string | null,
  ph_rh_history_juvenile_arthritis?: string | null,
  ph_rh_history_vasculitis?: string | null,
  ph_rh_history_lupus?: string | null,
  ph_rh_history_rheumatoid?: string | null,
  ph_rh_history_spondyloarthropathy?: string | null,
  ph_rh_history_osteoporosis?: string | null,
  ph_past_medical_history?: string | null,
  ph_past_surgery_history?: string | null,
  ph_smoke?: string | null,
  ph_drugs?: string | null,
  ph_alcohol?: string | null,
  ph_alcohol_weekly?: string | null,
  ph_sleep?: string | null,
  ph_exercise?: string | null,
  ph_travel?: string | null,
  ph_pregnant?: string | null,
  ph_live_births?: string | null,
  ph_complications?: string | null,
  ad_people_in_household?: string | null,
  ph_symptoms?: Array< string > | null,
};

export type DeletePatientHistoryInput = {
  id: string,
};

export type CreateRapid3Input = {
  id?: string | null,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  ad_dress_yourself: string,
  ad_get_in_out_bed: string,
  ad_lift_full_cup_mouth: string,
  ad_walk_outdoor_flat: string,
  ad_wash_dry_body: string,
  ad_pick_clothing_floor: string,
  ad_turn_faucets_on_off: string,
  ad_get_in_out_car_bus_train_plane: string,
  ad_walk_two_miles: string,
  ad_recreational_activities_sports: string,
  ad_good_night_sleep: string,
  ad_deal_anxiety_nervous: string,
  ad_deal_depression_blue: string,
  ad_daily_pain_scale?: number | null,
  ad_how_well_doing_scale?: number | null,
};

export type ModelRapid3ConditionInput = {
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  ad_dress_yourself?: ModelStringInput | null,
  ad_get_in_out_bed?: ModelStringInput | null,
  ad_lift_full_cup_mouth?: ModelStringInput | null,
  ad_walk_outdoor_flat?: ModelStringInput | null,
  ad_wash_dry_body?: ModelStringInput | null,
  ad_pick_clothing_floor?: ModelStringInput | null,
  ad_turn_faucets_on_off?: ModelStringInput | null,
  ad_get_in_out_car_bus_train_plane?: ModelStringInput | null,
  ad_walk_two_miles?: ModelStringInput | null,
  ad_recreational_activities_sports?: ModelStringInput | null,
  ad_good_night_sleep?: ModelStringInput | null,
  ad_deal_anxiety_nervous?: ModelStringInput | null,
  ad_deal_depression_blue?: ModelStringInput | null,
  ad_daily_pain_scale?: ModelFloatInput | null,
  ad_how_well_doing_scale?: ModelFloatInput | null,
  and?: Array< ModelRapid3ConditionInput | null > | null,
  or?: Array< ModelRapid3ConditionInput | null > | null,
  not?: ModelRapid3ConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Rapid3 = {
  __typename: "Rapid3",
  id: string,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  ad_dress_yourself: string,
  ad_get_in_out_bed: string,
  ad_lift_full_cup_mouth: string,
  ad_walk_outdoor_flat: string,
  ad_wash_dry_body: string,
  ad_pick_clothing_floor: string,
  ad_turn_faucets_on_off: string,
  ad_get_in_out_car_bus_train_plane: string,
  ad_walk_two_miles: string,
  ad_recreational_activities_sports: string,
  ad_good_night_sleep: string,
  ad_deal_anxiety_nervous: string,
  ad_deal_depression_blue: string,
  ad_daily_pain_scale?: number | null,
  ad_how_well_doing_scale?: number | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateRapid3Input = {
  id: string,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
  ad_dress_yourself?: string | null,
  ad_get_in_out_bed?: string | null,
  ad_lift_full_cup_mouth?: string | null,
  ad_walk_outdoor_flat?: string | null,
  ad_wash_dry_body?: string | null,
  ad_pick_clothing_floor?: string | null,
  ad_turn_faucets_on_off?: string | null,
  ad_get_in_out_car_bus_train_plane?: string | null,
  ad_walk_two_miles?: string | null,
  ad_recreational_activities_sports?: string | null,
  ad_good_night_sleep?: string | null,
  ad_deal_anxiety_nervous?: string | null,
  ad_deal_depression_blue?: string | null,
  ad_daily_pain_scale?: number | null,
  ad_how_well_doing_scale?: number | null,
};

export type DeleteRapid3Input = {
  id: string,
};

export type CreatePrivacyNoticeInput = {
  id?: string | null,
  full_name?: string | null,
  authorized_1?: string | null,
  relationship_1?: string | null,
  authorized_2?: string | null,
  relationship_2?: string | null,
  authorized_3?: string | null,
  relationship_3?: string | null,
  decline?: boolean | null,
  date: string,
  open_payment_signature: string,
  open_payment_date: string,
  signature: string,
  first_name: string,
  last_name: string,
  date_of_birth: string,
};

export type ModelPrivacyNoticeConditionInput = {
  full_name?: ModelStringInput | null,
  authorized_1?: ModelStringInput | null,
  relationship_1?: ModelStringInput | null,
  authorized_2?: ModelStringInput | null,
  relationship_2?: ModelStringInput | null,
  authorized_3?: ModelStringInput | null,
  relationship_3?: ModelStringInput | null,
  decline?: ModelBooleanInput | null,
  date?: ModelStringInput | null,
  open_payment_signature?: ModelStringInput | null,
  open_payment_date?: ModelStringInput | null,
  signature?: ModelStringInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  and?: Array< ModelPrivacyNoticeConditionInput | null > | null,
  or?: Array< ModelPrivacyNoticeConditionInput | null > | null,
  not?: ModelPrivacyNoticeConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type PrivacyNotice = {
  __typename: "PrivacyNotice",
  id: string,
  full_name?: string | null,
  authorized_1?: string | null,
  relationship_1?: string | null,
  authorized_2?: string | null,
  relationship_2?: string | null,
  authorized_3?: string | null,
  relationship_3?: string | null,
  decline?: boolean | null,
  date: string,
  open_payment_signature: string,
  open_payment_date: string,
  signature: string,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  createdAt: string,
  updatedAt: string,
};

export type UpdatePrivacyNoticeInput = {
  id: string,
  full_name?: string | null,
  authorized_1?: string | null,
  relationship_1?: string | null,
  authorized_2?: string | null,
  relationship_2?: string | null,
  authorized_3?: string | null,
  relationship_3?: string | null,
  decline?: boolean | null,
  date?: string | null,
  open_payment_signature?: string | null,
  open_payment_date?: string | null,
  signature?: string | null,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
};

export type DeletePrivacyNoticeInput = {
  id: string,
};

export type CreateNewPatientInput = {
  id?: string | null,
  date: string,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  gender: string,
  marital_status: string,
  ethnicity?: string | null,
  race?: string | null,
  primary_language?: string | null,
  address: string,
  city: string,
  state: string,
  zip: string,
  home_phone: string,
  work_phone?: string | null,
  mobile_phone?: string | null,
  email: string,
  social_security?: string | null,
  employer?: string | null,
  education: string,
  veteran: string,
  occupation: string,
  preferred_pharmacy?: string | null,
  insurance_primary_name: string,
  insurance_primary_id: string,
  insurance_primary_group?: string | null,
  insurance_primary_address?: string | null,
  insurance_primary_phone?: string | null,
  insurance_primary_insured_person?: string | null,
  insurance_primary_insured_person_relation?: string | null,
  insurance_secondary?: string | null,
  insurance_secondary_id?: string | null,
  insurance_secondary_group?: string | null,
  insurance_secondary_address?: string | null,
  insurance_secondary_phone?: string | null,
  primary_care_physician_name?: string | null,
  referring_physician_name: string,
  primary_care_physician_phone?: string | null,
  referring_physician_phone?: string | null,
  emergency_contact_name: string,
  full_time?: boolean | null,
  emergency_contact_relationship: string,
  signature_page_1: string,
  signature_page_1_date: string,
  emergency_contact_phone: string,
  insurance_primary_insured_person_dob?: string | null,
  race_other?: string | null,
};

export type ModelNewPatientConditionInput = {
  date?: ModelStringInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  gender?: ModelStringInput | null,
  marital_status?: ModelStringInput | null,
  ethnicity?: ModelStringInput | null,
  race?: ModelStringInput | null,
  primary_language?: ModelStringInput | null,
  address?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  home_phone?: ModelStringInput | null,
  work_phone?: ModelStringInput | null,
  mobile_phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  social_security?: ModelStringInput | null,
  employer?: ModelStringInput | null,
  education?: ModelStringInput | null,
  veteran?: ModelStringInput | null,
  occupation?: ModelStringInput | null,
  preferred_pharmacy?: ModelStringInput | null,
  insurance_primary_name?: ModelStringInput | null,
  insurance_primary_id?: ModelStringInput | null,
  insurance_primary_group?: ModelStringInput | null,
  insurance_primary_address?: ModelStringInput | null,
  insurance_primary_phone?: ModelStringInput | null,
  insurance_primary_insured_person?: ModelStringInput | null,
  insurance_primary_insured_person_relation?: ModelStringInput | null,
  insurance_secondary?: ModelStringInput | null,
  insurance_secondary_id?: ModelStringInput | null,
  insurance_secondary_group?: ModelStringInput | null,
  insurance_secondary_address?: ModelStringInput | null,
  insurance_secondary_phone?: ModelStringInput | null,
  primary_care_physician_name?: ModelStringInput | null,
  referring_physician_name?: ModelStringInput | null,
  primary_care_physician_phone?: ModelStringInput | null,
  referring_physician_phone?: ModelStringInput | null,
  emergency_contact_name?: ModelStringInput | null,
  full_time?: ModelBooleanInput | null,
  emergency_contact_relationship?: ModelStringInput | null,
  signature_page_1?: ModelStringInput | null,
  signature_page_1_date?: ModelStringInput | null,
  emergency_contact_phone?: ModelStringInput | null,
  insurance_primary_insured_person_dob?: ModelStringInput | null,
  race_other?: ModelStringInput | null,
  and?: Array< ModelNewPatientConditionInput | null > | null,
  or?: Array< ModelNewPatientConditionInput | null > | null,
  not?: ModelNewPatientConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type NewPatient = {
  __typename: "NewPatient",
  id: string,
  date: string,
  first_name: string,
  last_name: string,
  date_of_birth: string,
  gender: string,
  marital_status: string,
  ethnicity?: string | null,
  race?: string | null,
  primary_language?: string | null,
  address: string,
  city: string,
  state: string,
  zip: string,
  home_phone: string,
  work_phone?: string | null,
  mobile_phone?: string | null,
  email: string,
  social_security?: string | null,
  employer?: string | null,
  education: string,
  veteran: string,
  occupation: string,
  preferred_pharmacy?: string | null,
  insurance_primary_name: string,
  insurance_primary_id: string,
  insurance_primary_group?: string | null,
  insurance_primary_address?: string | null,
  insurance_primary_phone?: string | null,
  insurance_primary_insured_person?: string | null,
  insurance_primary_insured_person_relation?: string | null,
  insurance_secondary?: string | null,
  insurance_secondary_id?: string | null,
  insurance_secondary_group?: string | null,
  insurance_secondary_address?: string | null,
  insurance_secondary_phone?: string | null,
  primary_care_physician_name?: string | null,
  referring_physician_name: string,
  primary_care_physician_phone?: string | null,
  referring_physician_phone?: string | null,
  emergency_contact_name: string,
  full_time?: boolean | null,
  emergency_contact_relationship: string,
  signature_page_1: string,
  signature_page_1_date: string,
  emergency_contact_phone: string,
  insurance_primary_insured_person_dob?: string | null,
  race_other?: string | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateNewPatientInput = {
  id: string,
  date?: string | null,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
  gender?: string | null,
  marital_status?: string | null,
  ethnicity?: string | null,
  race?: string | null,
  primary_language?: string | null,
  address?: string | null,
  city?: string | null,
  state?: string | null,
  zip?: string | null,
  home_phone?: string | null,
  work_phone?: string | null,
  mobile_phone?: string | null,
  email?: string | null,
  social_security?: string | null,
  employer?: string | null,
  education?: string | null,
  veteran?: string | null,
  occupation?: string | null,
  preferred_pharmacy?: string | null,
  insurance_primary_name?: string | null,
  insurance_primary_id?: string | null,
  insurance_primary_group?: string | null,
  insurance_primary_address?: string | null,
  insurance_primary_phone?: string | null,
  insurance_primary_insured_person?: string | null,
  insurance_primary_insured_person_relation?: string | null,
  insurance_secondary?: string | null,
  insurance_secondary_id?: string | null,
  insurance_secondary_group?: string | null,
  insurance_secondary_address?: string | null,
  insurance_secondary_phone?: string | null,
  primary_care_physician_name?: string | null,
  referring_physician_name?: string | null,
  primary_care_physician_phone?: string | null,
  referring_physician_phone?: string | null,
  emergency_contact_name?: string | null,
  full_time?: boolean | null,
  emergency_contact_relationship?: string | null,
  signature_page_1?: string | null,
  signature_page_1_date?: string | null,
  emergency_contact_phone?: string | null,
  insurance_primary_insured_person_dob?: string | null,
  race_other?: string | null,
};

export type DeleteNewPatientInput = {
  id: string,
};

export type ModelPatientHistoryFilterInput = {
  id?: ModelIDInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  ph_briefly_describe_present_symptoms?: ModelStringInput | null,
  ph_previous_treatment_for_problem?: ModelStringInput | null,
  ph_current_medicines?: ModelStringInput | null,
  ph_allergy_to_med?: ModelBooleanInput | null,
  ph_allergy_to_med_list?: ModelStringInput | null,
  ph_rh_history_osteoarthritis?: ModelStringInput | null,
  ph_rh_history_gout?: ModelStringInput | null,
  ph_rh_history_juvenile_arthritis?: ModelStringInput | null,
  ph_rh_history_vasculitis?: ModelStringInput | null,
  ph_rh_history_lupus?: ModelStringInput | null,
  ph_rh_history_rheumatoid?: ModelStringInput | null,
  ph_rh_history_spondyloarthropathy?: ModelStringInput | null,
  ph_rh_history_osteoporosis?: ModelStringInput | null,
  ph_past_medical_history?: ModelStringInput | null,
  ph_past_surgery_history?: ModelStringInput | null,
  ph_smoke?: ModelStringInput | null,
  ph_drugs?: ModelStringInput | null,
  ph_alcohol?: ModelStringInput | null,
  ph_alcohol_weekly?: ModelStringInput | null,
  ph_sleep?: ModelStringInput | null,
  ph_exercise?: ModelStringInput | null,
  ph_travel?: ModelStringInput | null,
  ph_pregnant?: ModelStringInput | null,
  ph_live_births?: ModelStringInput | null,
  ph_complications?: ModelStringInput | null,
  ad_people_in_household?: ModelStringInput | null,
  ph_symptoms?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelPatientHistoryFilterInput | null > | null,
  or?: Array< ModelPatientHistoryFilterInput | null > | null,
  not?: ModelPatientHistoryFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelPatientHistoryConnection = {
  __typename: "ModelPatientHistoryConnection",
  items:  Array<PatientHistory | null >,
  nextToken?: string | null,
};

export type ModelRapid3FilterInput = {
  id?: ModelIDInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  ad_dress_yourself?: ModelStringInput | null,
  ad_get_in_out_bed?: ModelStringInput | null,
  ad_lift_full_cup_mouth?: ModelStringInput | null,
  ad_walk_outdoor_flat?: ModelStringInput | null,
  ad_wash_dry_body?: ModelStringInput | null,
  ad_pick_clothing_floor?: ModelStringInput | null,
  ad_turn_faucets_on_off?: ModelStringInput | null,
  ad_get_in_out_car_bus_train_plane?: ModelStringInput | null,
  ad_walk_two_miles?: ModelStringInput | null,
  ad_recreational_activities_sports?: ModelStringInput | null,
  ad_good_night_sleep?: ModelStringInput | null,
  ad_deal_anxiety_nervous?: ModelStringInput | null,
  ad_deal_depression_blue?: ModelStringInput | null,
  ad_daily_pain_scale?: ModelFloatInput | null,
  ad_how_well_doing_scale?: ModelFloatInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelRapid3FilterInput | null > | null,
  or?: Array< ModelRapid3FilterInput | null > | null,
  not?: ModelRapid3FilterInput | null,
};

export type ModelRapid3Connection = {
  __typename: "ModelRapid3Connection",
  items:  Array<Rapid3 | null >,
  nextToken?: string | null,
};

export type ModelPrivacyNoticeFilterInput = {
  id?: ModelIDInput | null,
  full_name?: ModelStringInput | null,
  authorized_1?: ModelStringInput | null,
  relationship_1?: ModelStringInput | null,
  authorized_2?: ModelStringInput | null,
  relationship_2?: ModelStringInput | null,
  authorized_3?: ModelStringInput | null,
  relationship_3?: ModelStringInput | null,
  decline?: ModelBooleanInput | null,
  date?: ModelStringInput | null,
  open_payment_signature?: ModelStringInput | null,
  open_payment_date?: ModelStringInput | null,
  signature?: ModelStringInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelPrivacyNoticeFilterInput | null > | null,
  or?: Array< ModelPrivacyNoticeFilterInput | null > | null,
  not?: ModelPrivacyNoticeFilterInput | null,
};

export type ModelPrivacyNoticeConnection = {
  __typename: "ModelPrivacyNoticeConnection",
  items:  Array<PrivacyNotice | null >,
  nextToken?: string | null,
};

export type ModelNewPatientFilterInput = {
  id?: ModelIDInput | null,
  date?: ModelStringInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  gender?: ModelStringInput | null,
  marital_status?: ModelStringInput | null,
  ethnicity?: ModelStringInput | null,
  race?: ModelStringInput | null,
  primary_language?: ModelStringInput | null,
  address?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  home_phone?: ModelStringInput | null,
  work_phone?: ModelStringInput | null,
  mobile_phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  social_security?: ModelStringInput | null,
  employer?: ModelStringInput | null,
  education?: ModelStringInput | null,
  veteran?: ModelStringInput | null,
  occupation?: ModelStringInput | null,
  preferred_pharmacy?: ModelStringInput | null,
  insurance_primary_name?: ModelStringInput | null,
  insurance_primary_id?: ModelStringInput | null,
  insurance_primary_group?: ModelStringInput | null,
  insurance_primary_address?: ModelStringInput | null,
  insurance_primary_phone?: ModelStringInput | null,
  insurance_primary_insured_person?: ModelStringInput | null,
  insurance_primary_insured_person_relation?: ModelStringInput | null,
  insurance_secondary?: ModelStringInput | null,
  insurance_secondary_id?: ModelStringInput | null,
  insurance_secondary_group?: ModelStringInput | null,
  insurance_secondary_address?: ModelStringInput | null,
  insurance_secondary_phone?: ModelStringInput | null,
  primary_care_physician_name?: ModelStringInput | null,
  referring_physician_name?: ModelStringInput | null,
  primary_care_physician_phone?: ModelStringInput | null,
  referring_physician_phone?: ModelStringInput | null,
  emergency_contact_name?: ModelStringInput | null,
  full_time?: ModelBooleanInput | null,
  emergency_contact_relationship?: ModelStringInput | null,
  signature_page_1?: ModelStringInput | null,
  signature_page_1_date?: ModelStringInput | null,
  emergency_contact_phone?: ModelStringInput | null,
  insurance_primary_insured_person_dob?: ModelStringInput | null,
  race_other?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelNewPatientFilterInput | null > | null,
  or?: Array< ModelNewPatientFilterInput | null > | null,
  not?: ModelNewPatientFilterInput | null,
};

export type ModelNewPatientConnection = {
  __typename: "ModelNewPatientConnection",
  items:  Array<NewPatient | null >,
  nextToken?: string | null,
};

export type ModelSubscriptionPatientHistoryFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  first_name?: ModelSubscriptionStringInput | null,
  last_name?: ModelSubscriptionStringInput | null,
  date_of_birth?: ModelSubscriptionStringInput | null,
  ph_briefly_describe_present_symptoms?: ModelSubscriptionStringInput | null,
  ph_previous_treatment_for_problem?: ModelSubscriptionStringInput | null,
  ph_current_medicines?: ModelSubscriptionStringInput | null,
  ph_allergy_to_med?: ModelSubscriptionBooleanInput | null,
  ph_allergy_to_med_list?: ModelSubscriptionStringInput | null,
  ph_rh_history_osteoarthritis?: ModelSubscriptionStringInput | null,
  ph_rh_history_gout?: ModelSubscriptionStringInput | null,
  ph_rh_history_juvenile_arthritis?: ModelSubscriptionStringInput | null,
  ph_rh_history_vasculitis?: ModelSubscriptionStringInput | null,
  ph_rh_history_lupus?: ModelSubscriptionStringInput | null,
  ph_rh_history_rheumatoid?: ModelSubscriptionStringInput | null,
  ph_rh_history_spondyloarthropathy?: ModelSubscriptionStringInput | null,
  ph_rh_history_osteoporosis?: ModelSubscriptionStringInput | null,
  ph_past_medical_history?: ModelSubscriptionStringInput | null,
  ph_past_surgery_history?: ModelSubscriptionStringInput | null,
  ph_smoke?: ModelSubscriptionStringInput | null,
  ph_drugs?: ModelSubscriptionStringInput | null,
  ph_alcohol?: ModelSubscriptionStringInput | null,
  ph_alcohol_weekly?: ModelSubscriptionStringInput | null,
  ph_sleep?: ModelSubscriptionStringInput | null,
  ph_exercise?: ModelSubscriptionStringInput | null,
  ph_travel?: ModelSubscriptionStringInput | null,
  ph_pregnant?: ModelSubscriptionStringInput | null,
  ph_live_births?: ModelSubscriptionStringInput | null,
  ph_complications?: ModelSubscriptionStringInput | null,
  ad_people_in_household?: ModelSubscriptionStringInput | null,
  ph_symptoms?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionPatientHistoryFilterInput | null > | null,
  or?: Array< ModelSubscriptionPatientHistoryFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type ModelSubscriptionRapid3FilterInput = {
  id?: ModelSubscriptionIDInput | null,
  first_name?: ModelSubscriptionStringInput | null,
  last_name?: ModelSubscriptionStringInput | null,
  date_of_birth?: ModelSubscriptionStringInput | null,
  ad_dress_yourself?: ModelSubscriptionStringInput | null,
  ad_get_in_out_bed?: ModelSubscriptionStringInput | null,
  ad_lift_full_cup_mouth?: ModelSubscriptionStringInput | null,
  ad_walk_outdoor_flat?: ModelSubscriptionStringInput | null,
  ad_wash_dry_body?: ModelSubscriptionStringInput | null,
  ad_pick_clothing_floor?: ModelSubscriptionStringInput | null,
  ad_turn_faucets_on_off?: ModelSubscriptionStringInput | null,
  ad_get_in_out_car_bus_train_plane?: ModelSubscriptionStringInput | null,
  ad_walk_two_miles?: ModelSubscriptionStringInput | null,
  ad_recreational_activities_sports?: ModelSubscriptionStringInput | null,
  ad_good_night_sleep?: ModelSubscriptionStringInput | null,
  ad_deal_anxiety_nervous?: ModelSubscriptionStringInput | null,
  ad_deal_depression_blue?: ModelSubscriptionStringInput | null,
  ad_daily_pain_scale?: ModelSubscriptionFloatInput | null,
  ad_how_well_doing_scale?: ModelSubscriptionFloatInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionRapid3FilterInput | null > | null,
  or?: Array< ModelSubscriptionRapid3FilterInput | null > | null,
};

export type ModelSubscriptionFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  in?: Array< number | null > | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionPrivacyNoticeFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  full_name?: ModelSubscriptionStringInput | null,
  authorized_1?: ModelSubscriptionStringInput | null,
  relationship_1?: ModelSubscriptionStringInput | null,
  authorized_2?: ModelSubscriptionStringInput | null,
  relationship_2?: ModelSubscriptionStringInput | null,
  authorized_3?: ModelSubscriptionStringInput | null,
  relationship_3?: ModelSubscriptionStringInput | null,
  decline?: ModelSubscriptionBooleanInput | null,
  date?: ModelSubscriptionStringInput | null,
  open_payment_signature?: ModelSubscriptionStringInput | null,
  open_payment_date?: ModelSubscriptionStringInput | null,
  signature?: ModelSubscriptionStringInput | null,
  first_name?: ModelSubscriptionStringInput | null,
  last_name?: ModelSubscriptionStringInput | null,
  date_of_birth?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionPrivacyNoticeFilterInput | null > | null,
  or?: Array< ModelSubscriptionPrivacyNoticeFilterInput | null > | null,
};

export type ModelSubscriptionNewPatientFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  date?: ModelSubscriptionStringInput | null,
  first_name?: ModelSubscriptionStringInput | null,
  last_name?: ModelSubscriptionStringInput | null,
  date_of_birth?: ModelSubscriptionStringInput | null,
  gender?: ModelSubscriptionStringInput | null,
  marital_status?: ModelSubscriptionStringInput | null,
  ethnicity?: ModelSubscriptionStringInput | null,
  race?: ModelSubscriptionStringInput | null,
  primary_language?: ModelSubscriptionStringInput | null,
  address?: ModelSubscriptionStringInput | null,
  city?: ModelSubscriptionStringInput | null,
  state?: ModelSubscriptionStringInput | null,
  zip?: ModelSubscriptionStringInput | null,
  home_phone?: ModelSubscriptionStringInput | null,
  work_phone?: ModelSubscriptionStringInput | null,
  mobile_phone?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  social_security?: ModelSubscriptionStringInput | null,
  employer?: ModelSubscriptionStringInput | null,
  education?: ModelSubscriptionStringInput | null,
  veteran?: ModelSubscriptionStringInput | null,
  occupation?: ModelSubscriptionStringInput | null,
  preferred_pharmacy?: ModelSubscriptionStringInput | null,
  insurance_primary_name?: ModelSubscriptionStringInput | null,
  insurance_primary_id?: ModelSubscriptionStringInput | null,
  insurance_primary_group?: ModelSubscriptionStringInput | null,
  insurance_primary_address?: ModelSubscriptionStringInput | null,
  insurance_primary_phone?: ModelSubscriptionStringInput | null,
  insurance_primary_insured_person?: ModelSubscriptionStringInput | null,
  insurance_primary_insured_person_relation?: ModelSubscriptionStringInput | null,
  insurance_secondary?: ModelSubscriptionStringInput | null,
  insurance_secondary_id?: ModelSubscriptionStringInput | null,
  insurance_secondary_group?: ModelSubscriptionStringInput | null,
  insurance_secondary_address?: ModelSubscriptionStringInput | null,
  insurance_secondary_phone?: ModelSubscriptionStringInput | null,
  primary_care_physician_name?: ModelSubscriptionStringInput | null,
  referring_physician_name?: ModelSubscriptionStringInput | null,
  primary_care_physician_phone?: ModelSubscriptionStringInput | null,
  referring_physician_phone?: ModelSubscriptionStringInput | null,
  emergency_contact_name?: ModelSubscriptionStringInput | null,
  full_time?: ModelSubscriptionBooleanInput | null,
  emergency_contact_relationship?: ModelSubscriptionStringInput | null,
  signature_page_1?: ModelSubscriptionStringInput | null,
  signature_page_1_date?: ModelSubscriptionStringInput | null,
  emergency_contact_phone?: ModelSubscriptionStringInput | null,
  insurance_primary_insured_person_dob?: ModelSubscriptionStringInput | null,
  race_other?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionNewPatientFilterInput | null > | null,
  or?: Array< ModelSubscriptionNewPatientFilterInput | null > | null,
};

export type CreatePatientHistoryMutationVariables = {
  input: CreatePatientHistoryInput,
  condition?: ModelPatientHistoryConditionInput | null,
};

export type CreatePatientHistoryMutation = {
  createPatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdatePatientHistoryMutationVariables = {
  input: UpdatePatientHistoryInput,
  condition?: ModelPatientHistoryConditionInput | null,
};

export type UpdatePatientHistoryMutation = {
  updatePatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeletePatientHistoryMutationVariables = {
  input: DeletePatientHistoryInput,
  condition?: ModelPatientHistoryConditionInput | null,
};

export type DeletePatientHistoryMutation = {
  deletePatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateRapid3MutationVariables = {
  input: CreateRapid3Input,
  condition?: ModelRapid3ConditionInput | null,
};

export type CreateRapid3Mutation = {
  createRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateRapid3MutationVariables = {
  input: UpdateRapid3Input,
  condition?: ModelRapid3ConditionInput | null,
};

export type UpdateRapid3Mutation = {
  updateRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteRapid3MutationVariables = {
  input: DeleteRapid3Input,
  condition?: ModelRapid3ConditionInput | null,
};

export type DeleteRapid3Mutation = {
  deleteRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreatePrivacyNoticeMutationVariables = {
  input: CreatePrivacyNoticeInput,
  condition?: ModelPrivacyNoticeConditionInput | null,
};

export type CreatePrivacyNoticeMutation = {
  createPrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdatePrivacyNoticeMutationVariables = {
  input: UpdatePrivacyNoticeInput,
  condition?: ModelPrivacyNoticeConditionInput | null,
};

export type UpdatePrivacyNoticeMutation = {
  updatePrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeletePrivacyNoticeMutationVariables = {
  input: DeletePrivacyNoticeInput,
  condition?: ModelPrivacyNoticeConditionInput | null,
};

export type DeletePrivacyNoticeMutation = {
  deletePrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateNewPatientMutationVariables = {
  input: CreateNewPatientInput,
  condition?: ModelNewPatientConditionInput | null,
};

export type CreateNewPatientMutation = {
  createNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateNewPatientMutationVariables = {
  input: UpdateNewPatientInput,
  condition?: ModelNewPatientConditionInput | null,
};

export type UpdateNewPatientMutation = {
  updateNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteNewPatientMutationVariables = {
  input: DeleteNewPatientInput,
  condition?: ModelNewPatientConditionInput | null,
};

export type DeleteNewPatientMutation = {
  deleteNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetPatientHistoryQueryVariables = {
  id: string,
};

export type GetPatientHistoryQuery = {
  getPatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListPatientHistoriesQueryVariables = {
  filter?: ModelPatientHistoryFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPatientHistoriesQuery = {
  listPatientHistories?:  {
    __typename: "ModelPatientHistoryConnection",
    items:  Array< {
      __typename: "PatientHistory",
      id: string,
      first_name: string,
      last_name: string,
      date_of_birth: string,
      ph_briefly_describe_present_symptoms: string,
      ph_previous_treatment_for_problem?: string | null,
      ph_current_medicines: string,
      ph_allergy_to_med: boolean,
      ph_allergy_to_med_list?: string | null,
      ph_rh_history_osteoarthritis?: string | null,
      ph_rh_history_gout?: string | null,
      ph_rh_history_juvenile_arthritis?: string | null,
      ph_rh_history_vasculitis?: string | null,
      ph_rh_history_lupus?: string | null,
      ph_rh_history_rheumatoid?: string | null,
      ph_rh_history_spondyloarthropathy?: string | null,
      ph_rh_history_osteoporosis?: string | null,
      ph_past_medical_history?: string | null,
      ph_past_surgery_history?: string | null,
      ph_smoke: string,
      ph_drugs: string,
      ph_alcohol: string,
      ph_alcohol_weekly?: string | null,
      ph_sleep?: string | null,
      ph_exercise?: string | null,
      ph_travel?: string | null,
      ph_pregnant?: string | null,
      ph_live_births?: string | null,
      ph_complications?: string | null,
      ad_people_in_household?: string | null,
      ph_symptoms: Array< string >,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetRapid3QueryVariables = {
  id: string,
};

export type GetRapid3Query = {
  getRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListRapid3sQueryVariables = {
  filter?: ModelRapid3FilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListRapid3sQuery = {
  listRapid3s?:  {
    __typename: "ModelRapid3Connection",
    items:  Array< {
      __typename: "Rapid3",
      id: string,
      first_name: string,
      last_name: string,
      date_of_birth: string,
      ad_dress_yourself: string,
      ad_get_in_out_bed: string,
      ad_lift_full_cup_mouth: string,
      ad_walk_outdoor_flat: string,
      ad_wash_dry_body: string,
      ad_pick_clothing_floor: string,
      ad_turn_faucets_on_off: string,
      ad_get_in_out_car_bus_train_plane: string,
      ad_walk_two_miles: string,
      ad_recreational_activities_sports: string,
      ad_good_night_sleep: string,
      ad_deal_anxiety_nervous: string,
      ad_deal_depression_blue: string,
      ad_daily_pain_scale?: number | null,
      ad_how_well_doing_scale?: number | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetPrivacyNoticeQueryVariables = {
  id: string,
};

export type GetPrivacyNoticeQuery = {
  getPrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListPrivacyNoticesQueryVariables = {
  filter?: ModelPrivacyNoticeFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPrivacyNoticesQuery = {
  listPrivacyNotices?:  {
    __typename: "ModelPrivacyNoticeConnection",
    items:  Array< {
      __typename: "PrivacyNotice",
      id: string,
      full_name?: string | null,
      authorized_1?: string | null,
      relationship_1?: string | null,
      authorized_2?: string | null,
      relationship_2?: string | null,
      authorized_3?: string | null,
      relationship_3?: string | null,
      decline?: boolean | null,
      date: string,
      open_payment_signature: string,
      open_payment_date: string,
      signature: string,
      first_name: string,
      last_name: string,
      date_of_birth: string,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetNewPatientQueryVariables = {
  id: string,
};

export type GetNewPatientQuery = {
  getNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListNewPatientsQueryVariables = {
  filter?: ModelNewPatientFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListNewPatientsQuery = {
  listNewPatients?:  {
    __typename: "ModelNewPatientConnection",
    items:  Array< {
      __typename: "NewPatient",
      id: string,
      date: string,
      first_name: string,
      last_name: string,
      date_of_birth: string,
      gender: string,
      marital_status: string,
      ethnicity?: string | null,
      race?: string | null,
      primary_language?: string | null,
      address: string,
      city: string,
      state: string,
      zip: string,
      home_phone: string,
      work_phone?: string | null,
      mobile_phone?: string | null,
      email: string,
      social_security?: string | null,
      employer?: string | null,
      education: string,
      veteran: string,
      occupation: string,
      preferred_pharmacy?: string | null,
      insurance_primary_name: string,
      insurance_primary_id: string,
      insurance_primary_group?: string | null,
      insurance_primary_address?: string | null,
      insurance_primary_phone?: string | null,
      insurance_primary_insured_person?: string | null,
      insurance_primary_insured_person_relation?: string | null,
      insurance_secondary?: string | null,
      insurance_secondary_id?: string | null,
      insurance_secondary_group?: string | null,
      insurance_secondary_address?: string | null,
      insurance_secondary_phone?: string | null,
      primary_care_physician_name?: string | null,
      referring_physician_name: string,
      primary_care_physician_phone?: string | null,
      referring_physician_phone?: string | null,
      emergency_contact_name: string,
      full_time?: boolean | null,
      emergency_contact_relationship: string,
      signature_page_1: string,
      signature_page_1_date: string,
      emergency_contact_phone: string,
      insurance_primary_insured_person_dob?: string | null,
      race_other?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreatePatientHistorySubscriptionVariables = {
  filter?: ModelSubscriptionPatientHistoryFilterInput | null,
};

export type OnCreatePatientHistorySubscription = {
  onCreatePatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdatePatientHistorySubscriptionVariables = {
  filter?: ModelSubscriptionPatientHistoryFilterInput | null,
};

export type OnUpdatePatientHistorySubscription = {
  onUpdatePatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeletePatientHistorySubscriptionVariables = {
  filter?: ModelSubscriptionPatientHistoryFilterInput | null,
};

export type OnDeletePatientHistorySubscription = {
  onDeletePatientHistory?:  {
    __typename: "PatientHistory",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ph_briefly_describe_present_symptoms: string,
    ph_previous_treatment_for_problem?: string | null,
    ph_current_medicines: string,
    ph_allergy_to_med: boolean,
    ph_allergy_to_med_list?: string | null,
    ph_rh_history_osteoarthritis?: string | null,
    ph_rh_history_gout?: string | null,
    ph_rh_history_juvenile_arthritis?: string | null,
    ph_rh_history_vasculitis?: string | null,
    ph_rh_history_lupus?: string | null,
    ph_rh_history_rheumatoid?: string | null,
    ph_rh_history_spondyloarthropathy?: string | null,
    ph_rh_history_osteoporosis?: string | null,
    ph_past_medical_history?: string | null,
    ph_past_surgery_history?: string | null,
    ph_smoke: string,
    ph_drugs: string,
    ph_alcohol: string,
    ph_alcohol_weekly?: string | null,
    ph_sleep?: string | null,
    ph_exercise?: string | null,
    ph_travel?: string | null,
    ph_pregnant?: string | null,
    ph_live_births?: string | null,
    ph_complications?: string | null,
    ad_people_in_household?: string | null,
    ph_symptoms: Array< string >,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateRapid3SubscriptionVariables = {
  filter?: ModelSubscriptionRapid3FilterInput | null,
};

export type OnCreateRapid3Subscription = {
  onCreateRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateRapid3SubscriptionVariables = {
  filter?: ModelSubscriptionRapid3FilterInput | null,
};

export type OnUpdateRapid3Subscription = {
  onUpdateRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteRapid3SubscriptionVariables = {
  filter?: ModelSubscriptionRapid3FilterInput | null,
};

export type OnDeleteRapid3Subscription = {
  onDeleteRapid3?:  {
    __typename: "Rapid3",
    id: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    ad_dress_yourself: string,
    ad_get_in_out_bed: string,
    ad_lift_full_cup_mouth: string,
    ad_walk_outdoor_flat: string,
    ad_wash_dry_body: string,
    ad_pick_clothing_floor: string,
    ad_turn_faucets_on_off: string,
    ad_get_in_out_car_bus_train_plane: string,
    ad_walk_two_miles: string,
    ad_recreational_activities_sports: string,
    ad_good_night_sleep: string,
    ad_deal_anxiety_nervous: string,
    ad_deal_depression_blue: string,
    ad_daily_pain_scale?: number | null,
    ad_how_well_doing_scale?: number | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreatePrivacyNoticeSubscriptionVariables = {
  filter?: ModelSubscriptionPrivacyNoticeFilterInput | null,
};

export type OnCreatePrivacyNoticeSubscription = {
  onCreatePrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdatePrivacyNoticeSubscriptionVariables = {
  filter?: ModelSubscriptionPrivacyNoticeFilterInput | null,
};

export type OnUpdatePrivacyNoticeSubscription = {
  onUpdatePrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeletePrivacyNoticeSubscriptionVariables = {
  filter?: ModelSubscriptionPrivacyNoticeFilterInput | null,
};

export type OnDeletePrivacyNoticeSubscription = {
  onDeletePrivacyNotice?:  {
    __typename: "PrivacyNotice",
    id: string,
    full_name?: string | null,
    authorized_1?: string | null,
    relationship_1?: string | null,
    authorized_2?: string | null,
    relationship_2?: string | null,
    authorized_3?: string | null,
    relationship_3?: string | null,
    decline?: boolean | null,
    date: string,
    open_payment_signature: string,
    open_payment_date: string,
    signature: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateNewPatientSubscriptionVariables = {
  filter?: ModelSubscriptionNewPatientFilterInput | null,
};

export type OnCreateNewPatientSubscription = {
  onCreateNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateNewPatientSubscriptionVariables = {
  filter?: ModelSubscriptionNewPatientFilterInput | null,
};

export type OnUpdateNewPatientSubscription = {
  onUpdateNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteNewPatientSubscriptionVariables = {
  filter?: ModelSubscriptionNewPatientFilterInput | null,
};

export type OnDeleteNewPatientSubscription = {
  onDeleteNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date: string,
    first_name: string,
    last_name: string,
    date_of_birth: string,
    gender: string,
    marital_status: string,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address: string,
    city: string,
    state: string,
    zip: string,
    home_phone: string,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email: string,
    social_security?: string | null,
    employer?: string | null,
    education: string,
    veteran: string,
    occupation: string,
    preferred_pharmacy?: string | null,
    insurance_primary_name: string,
    insurance_primary_id: string,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name: string,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name: string,
    full_time?: boolean | null,
    emergency_contact_relationship: string,
    signature_page_1: string,
    signature_page_1_date: string,
    emergency_contact_phone: string,
    insurance_primary_insured_person_dob?: string | null,
    race_other?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
