/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateNewPatientInput = {
  id?: string | null,
  date?: string | null,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
  gender?: string | null,
  marital_status?: string | null,
  ethnicity?: string | null,
  race?: string | null,
  primary_language?: string | null,
  address?: string | null,
  city?: string | null,
  state?: string | null,
  zip?: string | null,
  home_phone?: string | null,
  work_phone?: string | null,
  mobile_phone?: string | null,
  email?: string | null,
  social_security?: string | null,
  employer?: string | null,
  education?: string | null,
  veteran?: boolean | null,
  occupatin?: string | null,
  full_time?: boolean | null,
  preferred_pharmacy?: string | null,
  insurance_primary_name?: string | null,
  insurance_primary_id?: string | null,
  insurance_primary_group?: string | null,
  insurance_primary_address?: string | null,
  insurance_primary_phone?: string | null,
  insurance_primary_insured_person?: string | null,
  insurance_primary_insured_person_relation?: string | null,
  insurance_secondary?: string | null,
  insurance_secondary_id?: string | null,
  insurance_secondary_group?: string | null,
  insurance_secondary_address?: string | null,
  insurance_secondary_phone?: string | null,
  primary_care_physician_name?: string | null,
  referring_physician_name?: string | null,
  primary_care_physician_phone?: string | null,
  referring_physician_phone?: string | null,
  emergency_contact_name?: string | null,
  emergency_contact_phone?: string | null,
  emergency_contact_relationship?: string | null,
  signature_page_1?: string | null,
  signature_page_1_date?: string | null,
};

export type ModelNewPatientConditionInput = {
  date?: ModelStringInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  gender?: ModelStringInput | null,
  marital_status?: ModelStringInput | null,
  ethnicity?: ModelStringInput | null,
  race?: ModelStringInput | null,
  primary_language?: ModelStringInput | null,
  address?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  home_phone?: ModelStringInput | null,
  work_phone?: ModelStringInput | null,
  mobile_phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  social_security?: ModelStringInput | null,
  employer?: ModelStringInput | null,
  education?: ModelStringInput | null,
  veteran?: ModelBooleanInput | null,
  occupatin?: ModelStringInput | null,
  full_time?: ModelBooleanInput | null,
  preferred_pharmacy?: ModelStringInput | null,
  insurance_primary_name?: ModelStringInput | null,
  insurance_primary_id?: ModelStringInput | null,
  insurance_primary_group?: ModelStringInput | null,
  insurance_primary_address?: ModelStringInput | null,
  insurance_primary_phone?: ModelStringInput | null,
  insurance_primary_insured_person?: ModelStringInput | null,
  insurance_primary_insured_person_relation?: ModelStringInput | null,
  insurance_secondary?: ModelStringInput | null,
  insurance_secondary_id?: ModelStringInput | null,
  insurance_secondary_group?: ModelStringInput | null,
  insurance_secondary_address?: ModelStringInput | null,
  insurance_secondary_phone?: ModelStringInput | null,
  primary_care_physician_name?: ModelStringInput | null,
  referring_physician_name?: ModelStringInput | null,
  primary_care_physician_phone?: ModelStringInput | null,
  referring_physician_phone?: ModelStringInput | null,
  emergency_contact_name?: ModelStringInput | null,
  emergency_contact_phone?: ModelStringInput | null,
  emergency_contact_relationship?: ModelStringInput | null,
  signature_page_1?: ModelStringInput | null,
  signature_page_1_date?: ModelStringInput | null,
  and?: Array< ModelNewPatientConditionInput | null > | null,
  or?: Array< ModelNewPatientConditionInput | null > | null,
  not?: ModelNewPatientConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type NewPatient = {
  __typename: "NewPatient",
  id: string,
  date?: string | null,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
  gender?: string | null,
  marital_status?: string | null,
  ethnicity?: string | null,
  race?: string | null,
  primary_language?: string | null,
  address?: string | null,
  city?: string | null,
  state?: string | null,
  zip?: string | null,
  home_phone?: string | null,
  work_phone?: string | null,
  mobile_phone?: string | null,
  email?: string | null,
  social_security?: string | null,
  employer?: string | null,
  education?: string | null,
  veteran?: boolean | null,
  occupatin?: string | null,
  full_time?: boolean | null,
  preferred_pharmacy?: string | null,
  insurance_primary_name?: string | null,
  insurance_primary_id?: string | null,
  insurance_primary_group?: string | null,
  insurance_primary_address?: string | null,
  insurance_primary_phone?: string | null,
  insurance_primary_insured_person?: string | null,
  insurance_primary_insured_person_relation?: string | null,
  insurance_secondary?: string | null,
  insurance_secondary_id?: string | null,
  insurance_secondary_group?: string | null,
  insurance_secondary_address?: string | null,
  insurance_secondary_phone?: string | null,
  primary_care_physician_name?: string | null,
  referring_physician_name?: string | null,
  primary_care_physician_phone?: string | null,
  referring_physician_phone?: string | null,
  emergency_contact_name?: string | null,
  emergency_contact_phone?: string | null,
  emergency_contact_relationship?: string | null,
  signature_page_1?: string | null,
  signature_page_1_date?: string | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateNewPatientInput = {
  id: string,
  date?: string | null,
  first_name?: string | null,
  last_name?: string | null,
  date_of_birth?: string | null,
  gender?: string | null,
  marital_status?: string | null,
  ethnicity?: string | null,
  race?: string | null,
  primary_language?: string | null,
  address?: string | null,
  city?: string | null,
  state?: string | null,
  zip?: string | null,
  home_phone?: string | null,
  work_phone?: string | null,
  mobile_phone?: string | null,
  email?: string | null,
  social_security?: string | null,
  employer?: string | null,
  education?: string | null,
  veteran?: boolean | null,
  occupatin?: string | null,
  full_time?: boolean | null,
  preferred_pharmacy?: string | null,
  insurance_primary_name?: string | null,
  insurance_primary_id?: string | null,
  insurance_primary_group?: string | null,
  insurance_primary_address?: string | null,
  insurance_primary_phone?: string | null,
  insurance_primary_insured_person?: string | null,
  insurance_primary_insured_person_relation?: string | null,
  insurance_secondary?: string | null,
  insurance_secondary_id?: string | null,
  insurance_secondary_group?: string | null,
  insurance_secondary_address?: string | null,
  insurance_secondary_phone?: string | null,
  primary_care_physician_name?: string | null,
  referring_physician_name?: string | null,
  primary_care_physician_phone?: string | null,
  referring_physician_phone?: string | null,
  emergency_contact_name?: string | null,
  emergency_contact_phone?: string | null,
  emergency_contact_relationship?: string | null,
  signature_page_1?: string | null,
  signature_page_1_date?: string | null,
};

export type DeleteNewPatientInput = {
  id: string,
};

export type ModelNewPatientFilterInput = {
  id?: ModelIDInput | null,
  date?: ModelStringInput | null,
  first_name?: ModelStringInput | null,
  last_name?: ModelStringInput | null,
  date_of_birth?: ModelStringInput | null,
  gender?: ModelStringInput | null,
  marital_status?: ModelStringInput | null,
  ethnicity?: ModelStringInput | null,
  race?: ModelStringInput | null,
  primary_language?: ModelStringInput | null,
  address?: ModelStringInput | null,
  city?: ModelStringInput | null,
  state?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  home_phone?: ModelStringInput | null,
  work_phone?: ModelStringInput | null,
  mobile_phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  social_security?: ModelStringInput | null,
  employer?: ModelStringInput | null,
  education?: ModelStringInput | null,
  veteran?: ModelBooleanInput | null,
  occupatin?: ModelStringInput | null,
  full_time?: ModelBooleanInput | null,
  preferred_pharmacy?: ModelStringInput | null,
  insurance_primary_name?: ModelStringInput | null,
  insurance_primary_id?: ModelStringInput | null,
  insurance_primary_group?: ModelStringInput | null,
  insurance_primary_address?: ModelStringInput | null,
  insurance_primary_phone?: ModelStringInput | null,
  insurance_primary_insured_person?: ModelStringInput | null,
  insurance_primary_insured_person_relation?: ModelStringInput | null,
  insurance_secondary?: ModelStringInput | null,
  insurance_secondary_id?: ModelStringInput | null,
  insurance_secondary_group?: ModelStringInput | null,
  insurance_secondary_address?: ModelStringInput | null,
  insurance_secondary_phone?: ModelStringInput | null,
  primary_care_physician_name?: ModelStringInput | null,
  referring_physician_name?: ModelStringInput | null,
  primary_care_physician_phone?: ModelStringInput | null,
  referring_physician_phone?: ModelStringInput | null,
  emergency_contact_name?: ModelStringInput | null,
  emergency_contact_phone?: ModelStringInput | null,
  emergency_contact_relationship?: ModelStringInput | null,
  signature_page_1?: ModelStringInput | null,
  signature_page_1_date?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelNewPatientFilterInput | null > | null,
  or?: Array< ModelNewPatientFilterInput | null > | null,
  not?: ModelNewPatientFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelNewPatientConnection = {
  __typename: "ModelNewPatientConnection",
  items:  Array<NewPatient | null >,
  nextToken?: string | null,
};

export type ModelSubscriptionNewPatientFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  date?: ModelSubscriptionStringInput | null,
  first_name?: ModelSubscriptionStringInput | null,
  last_name?: ModelSubscriptionStringInput | null,
  date_of_birth?: ModelSubscriptionStringInput | null,
  gender?: ModelSubscriptionStringInput | null,
  marital_status?: ModelSubscriptionStringInput | null,
  ethnicity?: ModelSubscriptionStringInput | null,
  race?: ModelSubscriptionStringInput | null,
  primary_language?: ModelSubscriptionStringInput | null,
  address?: ModelSubscriptionStringInput | null,
  city?: ModelSubscriptionStringInput | null,
  state?: ModelSubscriptionStringInput | null,
  zip?: ModelSubscriptionStringInput | null,
  home_phone?: ModelSubscriptionStringInput | null,
  work_phone?: ModelSubscriptionStringInput | null,
  mobile_phone?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  social_security?: ModelSubscriptionStringInput | null,
  employer?: ModelSubscriptionStringInput | null,
  education?: ModelSubscriptionStringInput | null,
  veteran?: ModelSubscriptionBooleanInput | null,
  occupatin?: ModelSubscriptionStringInput | null,
  full_time?: ModelSubscriptionBooleanInput | null,
  preferred_pharmacy?: ModelSubscriptionStringInput | null,
  insurance_primary_name?: ModelSubscriptionStringInput | null,
  insurance_primary_id?: ModelSubscriptionStringInput | null,
  insurance_primary_group?: ModelSubscriptionStringInput | null,
  insurance_primary_address?: ModelSubscriptionStringInput | null,
  insurance_primary_phone?: ModelSubscriptionStringInput | null,
  insurance_primary_insured_person?: ModelSubscriptionStringInput | null,
  insurance_primary_insured_person_relation?: ModelSubscriptionStringInput | null,
  insurance_secondary?: ModelSubscriptionStringInput | null,
  insurance_secondary_id?: ModelSubscriptionStringInput | null,
  insurance_secondary_group?: ModelSubscriptionStringInput | null,
  insurance_secondary_address?: ModelSubscriptionStringInput | null,
  insurance_secondary_phone?: ModelSubscriptionStringInput | null,
  primary_care_physician_name?: ModelSubscriptionStringInput | null,
  referring_physician_name?: ModelSubscriptionStringInput | null,
  primary_care_physician_phone?: ModelSubscriptionStringInput | null,
  referring_physician_phone?: ModelSubscriptionStringInput | null,
  emergency_contact_name?: ModelSubscriptionStringInput | null,
  emergency_contact_phone?: ModelSubscriptionStringInput | null,
  emergency_contact_relationship?: ModelSubscriptionStringInput | null,
  signature_page_1?: ModelSubscriptionStringInput | null,
  signature_page_1_date?: ModelSubscriptionStringInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionNewPatientFilterInput | null > | null,
  or?: Array< ModelSubscriptionNewPatientFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type CreateNewPatientMutationVariables = {
  input: CreateNewPatientInput,
  condition?: ModelNewPatientConditionInput | null,
};

export type CreateNewPatientMutation = {
  createNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateNewPatientMutationVariables = {
  input: UpdateNewPatientInput,
  condition?: ModelNewPatientConditionInput | null,
};

export type UpdateNewPatientMutation = {
  updateNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteNewPatientMutationVariables = {
  input: DeleteNewPatientInput,
  condition?: ModelNewPatientConditionInput | null,
};

export type DeleteNewPatientMutation = {
  deleteNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetNewPatientQueryVariables = {
  id: string,
};

export type GetNewPatientQuery = {
  getNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListNewPatientsQueryVariables = {
  filter?: ModelNewPatientFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListNewPatientsQuery = {
  listNewPatients?:  {
    __typename: "ModelNewPatientConnection",
    items:  Array< {
      __typename: "NewPatient",
      id: string,
      date?: string | null,
      first_name?: string | null,
      last_name?: string | null,
      date_of_birth?: string | null,
      gender?: string | null,
      marital_status?: string | null,
      ethnicity?: string | null,
      race?: string | null,
      primary_language?: string | null,
      address?: string | null,
      city?: string | null,
      state?: string | null,
      zip?: string | null,
      home_phone?: string | null,
      work_phone?: string | null,
      mobile_phone?: string | null,
      email?: string | null,
      social_security?: string | null,
      employer?: string | null,
      education?: string | null,
      veteran?: boolean | null,
      occupatin?: string | null,
      full_time?: boolean | null,
      preferred_pharmacy?: string | null,
      insurance_primary_name?: string | null,
      insurance_primary_id?: string | null,
      insurance_primary_group?: string | null,
      insurance_primary_address?: string | null,
      insurance_primary_phone?: string | null,
      insurance_primary_insured_person?: string | null,
      insurance_primary_insured_person_relation?: string | null,
      insurance_secondary?: string | null,
      insurance_secondary_id?: string | null,
      insurance_secondary_group?: string | null,
      insurance_secondary_address?: string | null,
      insurance_secondary_phone?: string | null,
      primary_care_physician_name?: string | null,
      referring_physician_name?: string | null,
      primary_care_physician_phone?: string | null,
      referring_physician_phone?: string | null,
      emergency_contact_name?: string | null,
      emergency_contact_phone?: string | null,
      emergency_contact_relationship?: string | null,
      signature_page_1?: string | null,
      signature_page_1_date?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateNewPatientSubscriptionVariables = {
  filter?: ModelSubscriptionNewPatientFilterInput | null,
};

export type OnCreateNewPatientSubscription = {
  onCreateNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateNewPatientSubscriptionVariables = {
  filter?: ModelSubscriptionNewPatientFilterInput | null,
};

export type OnUpdateNewPatientSubscription = {
  onUpdateNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteNewPatientSubscriptionVariables = {
  filter?: ModelSubscriptionNewPatientFilterInput | null,
};

export type OnDeleteNewPatientSubscription = {
  onDeleteNewPatient?:  {
    __typename: "NewPatient",
    id: string,
    date?: string | null,
    first_name?: string | null,
    last_name?: string | null,
    date_of_birth?: string | null,
    gender?: string | null,
    marital_status?: string | null,
    ethnicity?: string | null,
    race?: string | null,
    primary_language?: string | null,
    address?: string | null,
    city?: string | null,
    state?: string | null,
    zip?: string | null,
    home_phone?: string | null,
    work_phone?: string | null,
    mobile_phone?: string | null,
    email?: string | null,
    social_security?: string | null,
    employer?: string | null,
    education?: string | null,
    veteran?: boolean | null,
    occupatin?: string | null,
    full_time?: boolean | null,
    preferred_pharmacy?: string | null,
    insurance_primary_name?: string | null,
    insurance_primary_id?: string | null,
    insurance_primary_group?: string | null,
    insurance_primary_address?: string | null,
    insurance_primary_phone?: string | null,
    insurance_primary_insured_person?: string | null,
    insurance_primary_insured_person_relation?: string | null,
    insurance_secondary?: string | null,
    insurance_secondary_id?: string | null,
    insurance_secondary_group?: string | null,
    insurance_secondary_address?: string | null,
    insurance_secondary_phone?: string | null,
    primary_care_physician_name?: string | null,
    referring_physician_name?: string | null,
    primary_care_physician_phone?: string | null,
    referring_physician_phone?: string | null,
    emergency_contact_name?: string | null,
    emergency_contact_phone?: string | null,
    emergency_contact_relationship?: string | null,
    signature_page_1?: string | null,
    signature_page_1_date?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
