import { generateClient } from "aws-amplify/api";
import { createNewPatient } from './graphql/mutations';

const client = generateClient()
const newNewPatient = await client.graphql({
    query: createNewPatient,
    variables: {
        input: {
		"date": "1970-01-01Z",
		"first_name": "Lorem ipsum dolor sit amet",
		"last_name": "Lorem ipsum dolor sit amet",
		"date_of_birth": "1970-01-01Z",
		"gender": "Lorem ipsum dolor sit amet",
		"marital_status": "Lorem ipsum dolor sit amet",
		"ethnicity": "Lorem ipsum dolor sit amet",
		"race": "Lorem ipsum dolor sit amet",
		"primary_language": "Lorem ipsum dolor sit amet",
		"address": "Lorem ipsum dolor sit amet",
		"city": "Lorem ipsum dolor sit amet",
		"state": "Lorem ipsum dolor sit amet",
		"zip": "Lorem ipsum dolor sit amet",
		"home_phone": "(555) 123-6789",
		"work_phone": "(555) 123-6789",
		"mobile_phone": "(555) 123-6789",
		"email": "Lorem ipsum dolor sit amet",
		"social_security": "Lorem ipsum dolor sit amet",
		"employer": "Lorem ipsum dolor sit amet",
		"education": "Lorem ipsum dolor sit amet",
		"veteran": true,
		"occupation": "Lorem ipsum dolor sit amet",
		"preferred_pharmacy": "Lorem ipsum dolor sit amet",
		"insurance_primary_name": "Lorem ipsum dolor sit amet",
		"insurance_primary_id": "Lorem ipsum dolor sit amet",
		"insurance_primary_group": "Lorem ipsum dolor sit amet",
		"insurance_primary_address": "Lorem ipsum dolor sit amet",
		"insurance_primary_phone": "(555) 123-6789",
		"insurance_primary_insured_person": "Lorem ipsum dolor sit amet",
		"insurance_primary_insured_person_relation": "Lorem ipsum dolor sit amet",
		"insurance_secondary": "Lorem ipsum dolor sit amet",
		"insurance_secondary_id": "Lorem ipsum dolor sit amet",
		"insurance_secondary_group": "Lorem ipsum dolor sit amet",
		"insurance_secondary_address": "Lorem ipsum dolor sit amet",
		"insurance_secondary_phone": "(555) 123-6789",
		"primary_care_physician_name": "Lorem ipsum dolor sit amet",
		"referring_physician_name": "Lorem ipsum dolor sit amet",
		"primary_care_physician_phone": "(555) 123-6789",
		"referring_physician_phone": "(555) 123-6789",
		"emergency_contact_name": "Lorem ipsum dolor sit amet",
		"full_time": true,
		"emergency_contact_relationship": "Lorem ipsum dolor sit amet",
		"signature_page_1": "Lorem ipsum dolor sit amet",
		"signature_page_1_date": "1970-01-01Z",
		"ph_briefly_describe_present_symptoms": "Lorem ipsum dolor sit amet",
		"ph_previous_treatment_for_problem": "Lorem ipsum dolor sit amet",
		"ph_current_medicines": "Lorem ipsum dolor sit amet",
		"emergency_contact_phone": "(555) 123-6789",
		"ph_allergy_to_med": true,
		"ph_allergy_to_med_list": "Lorem ipsum dolor sit amet",
		"ph_rh_history_osteoarthritis": "Lorem ipsum dolor sit amet",
		"ph_rh_history_gout": "Lorem ipsum dolor sit amet",
		"ph_rh_history_vasculitis": "Lorem ipsum dolor sit amet",
		"ph_rh_history_lupus": "Lorem ipsum dolor sit amet",
		"ph_rh_history_rheumatoid": "Lorem ipsum dolor sit amet",
		"ph_rh_history_spondyloarthropathy": "Lorem ipsum dolor sit amet",
		"ph_rh_history_osteoporosis": "Lorem ipsum dolor sit amet",
		"ph_past_medical_history": "Lorem ipsum dolor sit amet",
		"ph_past_surgery_history": "Lorem ipsum dolor sit amet",
		"ph_smoke": "Lorem ipsum dolor sit amet",
		"ph_alcohol": "Lorem ipsum dolor sit amet",
		"ph_rh_history_juvenile_arthritis": "Lorem ipsum dolor sit amet",
		"ph_sleep": "Lorem ipsum dolor sit amet",
		"ph_exercise": "Lorem ipsum dolor sit amet",
		"ph_travel": "Lorem ipsum dolor sit amet",
		"ph_pregnant": "Lorem ipsum dolor sit amet",
		"ph_live_births": "Lorem ipsum dolor sit amet",
		"ph_complications": "Lorem ipsum dolor sit amet",
		"ph_drugs": "Lorem ipsum dolor sit amet",
		"ad_people_in_household": "Lorem ipsum dolor sit amet",
		"ad_dress_yourself": "Lorem ipsum dolor sit amet",
		"ad_get_in_out_bed": "Lorem ipsum dolor sit amet",
		"ad_lift_full_cup_mouth": "Lorem ipsum dolor sit amet",
		"ad_walk_outdoor_flat": "Lorem ipsum dolor sit amet",
		"ad_wash_dry_body": "Lorem ipsum dolor sit amet",
		"ad_pick_clothing_floor": "Lorem ipsum dolor sit amet",
		"ad_turn_faucets_on_off": "Lorem ipsum dolor sit amet",
		"ad_get_in_out_car_bus_train_plane": "Lorem ipsum dolor sit amet",
		"ad_walk_two_miles": "Lorem ipsum dolor sit amet",
		"ad_recreational_activities_sports": "Lorem ipsum dolor sit amet",
		"ad_good_night_sleep": "Lorem ipsum dolor sit amet",
		"ad_daily_pain_scale": 1020,
		"ad_how_well_doing_scale": 1020,
		"ph_alcohol_weekly": "Lorem ipsum dolor sit amet",
		"ph_symptoms": "Lorem ipsum dolor sit amet",
		"ad_deal_anxiety_nervous": "Lorem ipsum dolor sit amet",
		"ad_deal_depression_blue": "Lorem ipsum dolor sit amet"
	}
    }
});